use_frameworks!

target 'Mandoline_Example' do
  pod 'Mandoline', :path => '../'

  target 'Mandoline_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
  pod 'Nimble', '~> 7.0.2'
  end
end
